import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans, Manrope } from "next/font/google";
import { Providers } from "./provider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontHeading = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});

const fontBody = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
      <html lang="en" suppressHydrationWarning={true}>
        <body
          className={
            cn("antialiased", fontHeading.variable, fontBody.variable)}
        >
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
    );

}
